title: teachingRSE
logo: "/assets/images/logo.png"
description: >-
  A survey of resources for learning and teaching RSE.
twitter_username: RSE_de
github_username: de-RSE
minimal_mistakes_skin: default

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: Europe/Berlin

remote_theme: mmistakes/minimal-mistakes@4.19.1
baseurl: /learn-and-teach
repository: DE-RSE/learn-and-teach

include:
  - _pages

collections_dir: collections
collections:
  - resources

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

author:
  name   : "de-RSE e.V."
  avatar : "https://de-rse.org/assets/img/site/rse.png"
  bio    : "Gesellschaft für Forschungssoftware"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.de-rse.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RSE_de"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/de-rse"

footer:
  links:
    - label: "de-RSE main website"
      icon: "fas fa-fw fa-link"
      url: "https://www.de-rse.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RSE_de"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/de-RSE"
